server:
  port: 8031
spring:
  application:
    name: andlinks-cloud-hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
turbine:
  appConfig: andlinks-cloud-comsumer-user
  clusterNameExpression: "'default'"